/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;
import dao.NhaCungCapDAO;
import dao.impl.NhaCungCapDAOImpl;
import model.NhaCungCap;

/**
 *
 * @author Admin
 */
public class NhaCungCapForm extends javax.swing.JFrame {

    private transient NhaCungCapDAO nccDAO;
    private DefaultTableModel tableModel;

    /**
     * Creates new form NhaCungCapForm
     */
    public NhaCungCapForm() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.nccDAO = new NhaCungCapDAOImpl();
        initUiBehavior();
        initTrangThaiCombo();
        loadDataToTable(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cboTrangThai = new javax.swing.JComboBox<>();
        btnTimKiem = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhaCungCap = new javax.swing.JTable();
        txtEmail1 = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        btnMoi = new javax.swing.JButton();
        coTrangThaiChinhSua = new javax.swing.JComboBox<>();
        txtDiaChi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnSua = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtTenNhaCungCap = new javax.swing.JTextField();
        txtSoDienThoai = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(225, 177, 112));
        jPanel1.setForeground(new java.awt.Color(164, 115, 115));

        cboTrangThai.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cboTrangThai.setForeground(new java.awt.Color(164, 115, 115));
        cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(164, 115, 115));
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/find.png"))); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(164, 115, 115));
        jLabel3.setText("Địa Chỉ ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(164, 115, 115));
        jLabel4.setText("Số Điện Thoại");

        tblNhaCungCap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblNhaCungCap);

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        btnMoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMoi.setForeground(new java.awt.Color(164, 115, 115));
        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh.png"))); // NOI18N
        btnMoi.setText("Mới");

        coTrangThaiChinhSua.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        coTrangThaiChinhSua.setForeground(new java.awt.Color(164, 115, 115));
        coTrangThaiChinhSua.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(164, 115, 115));
        jLabel6.setText("Trạng Thái");

        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSua.setForeground(new java.awt.Color(164, 115, 115));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fix.png"))); // NOI18N
        btnSua.setText("Sửa");

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThem.setForeground(new java.awt.Color(164, 115, 115));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plus.png"))); // NOI18N
        btnThem.setText("Thêm");

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(164, 115, 115));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete_one.png"))); // NOI18N
        btnXoa.setText("Xóa");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(164, 115, 115));
        jLabel5.setText("Email");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(164, 115, 115));
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(164, 115, 115));
        jLabel2.setText("Nhà Cung Cấp");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSoDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(txtDiaChi)
                            .addComponent(txtTenNhaCungCap)
                            .addComponent(txtID)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(coTrangThaiChinhSua, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSua)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa)
                        .addGap(18, 18, 18)
                        .addComponent(btnMoi))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnTimKiem)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnMoi))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(coTrangThaiChinhSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    // ======= Added behavior: UI wiring and CRUD =======
    private void initUiBehavior() {
        tableModel = (DefaultTableModel) tblNhaCungCap.getModel();
        // Replace default placeholder model columns
        tableModel.setColumnIdentifiers(new Object[]{"ID", "TenNCC", "DiaChi", "SoDienThoai", "Email", "TrangThai", "CreatedAt"});

        // Clear placeholder texts if NetBeans left defaults
        clearPlaceholders();

        // Buttons
        btnThem.addActionListener(e -> onThem());
        btnSua.addActionListener(e -> onSua());
        btnXoa.addActionListener(e -> onXoa());
        btnMoi.addActionListener(e -> onMoi());
        btnTimKiem.addActionListener(e -> loadDataToTable(safeText(txtEmail1.getText())));

        // Enter key on search
        txtEmail1.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) loadDataToTable(safeText(txtEmail1.getText()));
            }
        });

        // Table selection -> fill form
        tblNhaCungCap.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int row = tblNhaCungCap.getSelectedRow();
                if (row >= 0) {
                    txtID.setText(String.valueOf(tableModel.getValueAt(row, 0)));
                    txtTenNhaCungCap.setText(String.valueOf(tableModel.getValueAt(row, 1)));
                    txtDiaChi.setText(String.valueOf(tableModel.getValueAt(row, 2)));
                    txtSoDienThoai.setText(String.valueOf(tableModel.getValueAt(row, 3)));
                    txtEmail.setText(String.valueOf(tableModel.getValueAt(row, 4)));
                    String tt = String.valueOf(tableModel.getValueAt(row, 5));
                    coTrangThaiChinhSua.setSelectedItem(tt);
                }
            }
        });
        if (!utils.Auth.isManager()) {
            btnThem.setEnabled(false);
            btnSua.setEnabled(false);
            btnXoa.setEnabled(false);
        }
    }

    private void initTrangThaiCombo() {
        DefaultComboBoxModel<String> m = new DefaultComboBoxModel<>();
        m.addElement("Tất cả");
        m.addElement("HopTac");
        m.addElement("Ngung");
        cboTrangThai.setModel(m);
        cboTrangThai.setSelectedIndex(0);

        DefaultComboBoxModel<String> mChinhSua = new DefaultComboBoxModel<>();
        mChinhSua.addElement("HopTac");
        mChinhSua.addElement("Ngung");
        coTrangThaiChinhSua.setModel(mChinhSua);
        coTrangThaiChinhSua.setSelectedIndex(0);
    }

    private String safeText(String s) { return s == null ? "" : s.trim(); }

    private void loadDataToTable(String keyword) {
        List<NhaCungCap> list = nccDAO.findAll();
        tableModel.setRowCount(0);
        String kw = safeText(keyword).toLowerCase();
        String filterTT = mapTrangThaiFilter((String) cboTrangThai.getSelectedItem());
        for (NhaCungCap n : list) {
            boolean match = kw.isEmpty() ||
                (n.getTenNCC() != null && n.getTenNCC().toLowerCase().contains(kw)) ||
                (n.getDiaChi() != null && n.getDiaChi().toLowerCase().contains(kw)) ||
                (n.getEmail() != null && n.getEmail().toLowerCase().contains(kw));
            String tt = toDbTrangThai(n);
            if (match && (filterTT == null || filterTT.equals(tt))) {
                tableModel.addRow(new Object[]{
                    n.getId(), n.getTenNCC(), n.getDiaChi(), n.getSoDienThoai(), n.getEmail(), tt, n.getCreatedAt()
                });
            }
        }
    }

    private String mapTrangThaiFilter(String sel) {
        if (sel == null || "Tất cả".equals(sel)) return null;
        return sel;
    }

    private String toDbTrangThai(NhaCungCap n) {
        if (n.getTrangThai() == null) return "HopTac";
        String t = n.getTrangThai().trim();
        if ("HopTac".equalsIgnoreCase(t) || "Hoptac".equalsIgnoreCase(t) || "1".equals(t)) return "HopTac";
        if ("Ngung".equalsIgnoreCase(t) || "0".equals(t)) return "Ngung";
        return t;
    }

    private Integer parseIdFromField() {
        String s = safeText(txtID.getText());
        if (s.isEmpty()) return null;
        try { return Integer.parseInt(s); } catch (NumberFormatException e) { return null; }
    }

    private NhaCungCap readFormForCreate() {
        String ten = safeText(txtTenNhaCungCap.getText());
        if (ten.isEmpty()) throw new IllegalArgumentException("Tên nhà cung cấp không được để trống");
        NhaCungCap n = new NhaCungCap();
        n.setTenNCC(ten);
        n.setDiaChi(safeText(txtDiaChi.getText()));
        n.setSoDienThoai(safeText(txtSoDienThoai.getText()));
        n.setEmail(safeText(txtEmail.getText()));
        String sel = (String) coTrangThaiChinhSua.getSelectedItem();
        n.setTrangThai(sel == null ? "HopTac" : sel);
        return n;
    }

    private NhaCungCap readFormForUpdate() {
        Integer id = parseIdFromField();
        if (id == null) throw new IllegalArgumentException("ID không hợp lệ");
        NhaCungCap n = readFormForCreate();
        n.setId(id);
        return n;
    }

    private void onThem() {
        if (!utils.Auth.isManager()) {
            utils.MsgBox.alert(this, "Bạn không có quyền thực hiện chức năng này!");
            return;
        }
        try {
            NhaCungCap n = readFormForCreate();
            Integer existed = null;
            try { existed = nccDAO.idByTen(n.getTenNCC()); } catch (Exception ignored) {}
            if (existed != null) { JOptionPane.showMessageDialog(this, "Tên nhà cung cấp đã tồn tại"); return; }
            Integer newId = nccDAO.insert(n);
            if (newId != null) {
                JOptionPane.showMessageDialog(this, "Thêm thành công");
                n.setId(newId);
                loadDataToTable(null);
                selectRowById(newId);
                clearForm();
            } else JOptionPane.showMessageDialog(this, "Thêm thất bại");
        } catch (IllegalArgumentException ex) { JOptionPane.showMessageDialog(this, ex.getMessage()); }
    }

    private void onSua() {
        if (!utils.Auth.isManager()) {
            utils.MsgBox.alert(this, "Bạn không có quyền thực hiện chức năng này!");
            return;
        }
        try {
            NhaCungCap n = readFormForUpdate();
            NhaCungCap existed = nccDAO.findById(n.getId());
            if (existed == null) { JOptionPane.showMessageDialog(this, "Không tìm thấy ID để sửa"); return; }
            boolean ok = nccDAO.update(n);
            if (ok) { JOptionPane.showMessageDialog(this, "Sửa thành công"); loadDataToTable(null); selectRowById(n.getId()); }
            else JOptionPane.showMessageDialog(this, "Sửa thất bại");
        } catch (IllegalArgumentException ex) { JOptionPane.showMessageDialog(this, ex.getMessage()); }
    }

    private void onXoa() {
        if (!utils.Auth.isManager()) {
            utils.MsgBox.alert(this, "Bạn không có quyền thực hiện chức năng này!");
            return;
        }
        try {
            Integer id = parseIdFromField();
            if (id == null) { JOptionPane.showMessageDialog(this, "Chọn bản ghi để xóa"); return; }
            int conf = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (conf != JOptionPane.YES_OPTION) return;
            boolean ok = nccDAO.delete(id);
            if (ok) { JOptionPane.showMessageDialog(this, "Xóa thành công"); loadDataToTable(null); clearForm(); }
            else JOptionPane.showMessageDialog(this, "Xóa thất bại");
        } catch (Exception ex) { JOptionPane.showMessageDialog(this, "Lỗi xóa: " + ex.getMessage()); }
    }

    private void onMoi() {
        clearForm();
    }

    private void selectRowById(Integer id) {
        if (id == null) return;
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            Object val = tableModel.getValueAt(i, 0);
            if (val != null && String.valueOf(val).equals(String.valueOf(id))) {
                tblNhaCungCap.setRowSelectionInterval(i, i);
                tblNhaCungCap.scrollRectToVisible(tblNhaCungCap.getCellRect(i, 0, true));
                break;
            }
        }
    }

    private void clearForm() {
        txtID.setText("");
        txtTenNhaCungCap.setText("");
        txtDiaChi.setText("");
        txtSoDienThoai.setText("");
        txtEmail.setText("");
        coTrangThaiChinhSua.setSelectedIndex(0);
        tblNhaCungCap.clearSelection();
    }

    private void clearPlaceholders() {
        if ("jTextField1".equals(txtID.getText())) txtID.setText("");
        if ("jTextField1".equals(txtTenNhaCungCap.getText())) txtTenNhaCungCap.setText("");
        if ("jTextField1".equals(txtDiaChi.getText())) txtDiaChi.setText("");
        if ("jTextField1".equals(txtSoDienThoai.getText())) txtSoDienThoai.setText("");
        if ("jTextField1".equals(txtEmail.getText())) txtEmail.setText("");
        if ("jTextField1".equals(txtEmail1.getText())) txtEmail1.setText("");
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhaCungCapForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhaCungCapForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhaCungCapForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhaCungCapForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhaCungCapForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboTrangThai;
    private javax.swing.JComboBox<String> coTrangThaiChinhSua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNhaCungCap;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenNhaCungCap;
    // End of variables declaration//GEN-END:variables
}
