package ui;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.List;
import dao.ThuongHieuDAO;
import dao.impl.ThuongHieuDAOImpl;
import model.ThuongHieu;

/**
 *
 * @author Admin
 */
public class ThuongHieuForm extends javax.swing.JFrame {

    // Thêm: DAO và model
    private transient ThuongHieuDAO thuongHieuDAO;
    private DefaultTableModel tableModel;

    /**
     * Creates new form ThuongHieuForm
     */
    public ThuongHieuForm() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.thuongHieuDAO = new ThuongHieuDAOImpl();
        initUiBehavior();
        // Khởi tạo combobox trạng thái thống nhất với DB
        initTrangThaiCombo();
        // Nạp dữ liệu
        loadDataToTable(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSearchThuongHieu = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        txtMaThuongHieu = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTenThuongHieu = new javax.swing.JTextField();
        btnXoa = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblTongThuongHieu = new javax.swing.JLabel();
        cboTrangThai = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblThuongHieu = new javax.swing.JTable();
        btnLoc = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(837, 499));

        jPanel1.setBackground(new java.awt.Color(225, 177, 112));
        jPanel1.setForeground(new java.awt.Color(164, 115, 115));
        jPanel1.setPreferredSize(new java.awt.Dimension(1500, 800));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(164, 115, 115));
        jLabel2.setText("Tên Thương Hiệu");

        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        jScrollPane1.setViewportView(txtMoTa);

        txtMaThuongHieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaThuongHieuActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(164, 115, 115));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plus.png"))); // NOI18N
        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(164, 115, 115));
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh.png"))); // NOI18N
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(164, 115, 115));
        jLabel1.setText("Mã Thương Hiệu");

        txtTenThuongHieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenThuongHieuActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(164, 115, 115));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete_one.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(164, 115, 115));
        jLabel3.setText("Tìm Kiếm");

        lblTongThuongHieu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTongThuongHieu.setForeground(new java.awt.Color(164, 115, 115));
        lblTongThuongHieu.setText("jLabel4");

        cboTrangThai.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cboTrangThai.setForeground(new java.awt.Color(164, 115, 115));
        cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(164, 115, 115));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fix.png"))); // NOI18N
        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tblThuongHieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã ", "Tên ", "Ghi Chú", "Trạng Thái"
            }
        ));
        jScrollPane2.setViewportView(tblThuongHieu);

        btnLoc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLoc.setForeground(new java.awt.Color(164, 115, 115));
        btnLoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filter.png"))); // NOI18N
        btnLoc.setText("Lọc");
        btnLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(164, 115, 115));
        jLabel4.setText("Ghi Chú");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtTenThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtMaThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSearchThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTongThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(827, 827, 827))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearchThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(btnLoc))
                        .addGap(155, 155, 155)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa)
                        .addGap(18, 18, 18)
                        .addComponent(btnLamMoi)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTongThuongHieu)
                        .addGap(163, 163, 163))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaThuongHieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaThuongHieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaThuongHieuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        onThem();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        onLamMoi();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void txtTenThuongHieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenThuongHieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenThuongHieuActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        onXoa();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        onSua();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocActionPerformed
        String keyword = safeText(txtSearchThuongHieu.getText());
        loadDataToTable(keyword);
    }//GEN-LAST:event_btnLocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThuongHieuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThuongHieuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThuongHieuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThuongHieuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThuongHieuForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLoc;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboTrangThai;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTongThuongHieu;
    private javax.swing.JTable tblThuongHieu;
    private javax.swing.JTextField txtMaThuongHieu;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtSearchThuongHieu;
    private javax.swing.JTextField txtTenThuongHieu;
    // End of variables declaration//GEN-END:variables

    // ==== Bổ sung code tiện ích và xử lý ====

    private void initUiBehavior() {
        // Chuẩn bị model bảng
        tableModel = (DefaultTableModel) tblThuongHieu.getModel();
        txtMaThuongHieu.setEditable(false);


        // Xóa placeholder mặc định
        clearPlaceholders();

        // Bắt sự kiện gõ Enter trong ô tìm kiếm
        txtSearchThuongHieu.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    btnLocActionPerformed(null);
                }
            }
        });

        // Chọn dòng -> đổ dữ liệu lên form
        tblThuongHieu.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                boolean isRowSelected = tblThuongHieu.getSelectedRow() >= 0;
                updateButtonStates(isRowSelected);

                if (isRowSelected) {
                    int row = tblThuongHieu.getSelectedRow();
                    txtMaThuongHieu.setText(String.valueOf(tblThuongHieu.getValueAt(row, 0)));
                    txtTenThuongHieu.setText(String.valueOf(tblThuongHieu.getValueAt(row, 1)));
                    txtMoTa.setText(String.valueOf(tblThuongHieu.getValueAt(row, 2)));
                    String ttText = String.valueOf(tblThuongHieu.getValueAt(row, 3));
                    cboTrangThai.setSelectedItem(ttText);
                }
            }
        });

        updateButtonStates(false); // Initial state
    }

    private void updateButtonStates(boolean rowIsSelected) {
        boolean isManager = utils.Auth.isManager();
        
        jButton1.setEnabled(!rowIsSelected && isManager); // Thêm
        jButton2.setEnabled(rowIsSelected && isManager); // Sửa
        btnXoa.setEnabled(rowIsSelected && isManager); // Xóa
    }
    
    private void initTrangThaiCombo() {
        // UI: "Tất cả", "HoatDong", "NgungDung" để khớp DB
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement("Tất cả");
        model.addElement("HoatDong");
        model.addElement("NgungDung");
        cboTrangThai.setModel(model);
        cboTrangThai.setSelectedIndex(0);
    }
    
    private void onThem() {
        if (!utils.Auth.isManager()) {
            utils.MsgBox.alert(this, "Bạn không có quyền thực hiện chức năng này!");
            return;
        }
        try {
            ThuongHieu th = readFormForCreate();
            // Kiểm tra trùng tên (nếu có API idByTen)
            Integer existedId = null;
            try { existedId = thuongHieuDAO.idByTen(th.getTenThuongHieu()); } catch (Exception ignored) {}
            if (existedId != null) {
                JOptionPane.showMessageDialog(this, "Tên thương hiệu đã tồn tại!");
                return;
            }
            // insert
            if (safeInsert(th)) {
                JOptionPane.showMessageDialog(this, "Thêm thành công");
                loadDataToTable(null);
                selectRowById(th.getId()); // nếu DAO trả id vào entity; nếu không, chỉ refresh
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
            }
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi thêm: " + ex.getMessage());
        }
    }
    
    private void onSua() {
        if (!utils.Auth.isManager()) {
            utils.MsgBox.alert(this, "Bạn không có quyền thực hiện chức năng này!");
            return;
        }
        try {
            ThuongHieu th = readFormForUpdate();
            ThuongHieu existed = thuongHieuDAO.findById(th.getId());
            if (existed == null) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy ID để sửa");
                return;
            }
            if (safeUpdate(th)) {
                JOptionPane.showMessageDialog(this, "Sửa thành công");
                loadDataToTable(null);
                selectRowById(th.getId());
            } else {
                JOptionPane.showMessageDialog(this, "Sửa thất bại");
            }
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi sửa: " + ex.getMessage());
        }
    }
    
    private void onXoa() {
        if (!utils.Auth.isManager()) {
            utils.MsgBox.alert(this, "Bạn không có quyền thực hiện chức năng này!");
            return;
        }
        try {
            Integer id = parseIdFromField();
            if (id == null) {
                JOptionPane.showMessageDialog(this, "Chọn bản ghi để xóa");
                return;
            }
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (confirm != JOptionPane.YES_OPTION) return;

            boolean ok = safeDelete(id);
            if (ok) {
                JOptionPane.showMessageDialog(this, "Xóa thành công");
                loadDataToTable(null);
                clearForm();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi xóa: " + ex.getMessage());
        }
    }
    
    private void onLamMoi() {
        clearForm();
        cboTrangThai.setSelectedIndex(0);
        txtSearchThuongHieu.setText("");
        loadDataToTable(null);
    }
    
    private ThuongHieu readFormForCreate() {
        String ten = safeText(txtTenThuongHieu.getText());
        if (ten.isEmpty()) throw new IllegalArgumentException("Tên thương hiệu không được để trống");
        String moTa = safeText(txtMoTa.getText());
        String ttDb = mapTrangThaiValueFromCombo(); // trả về "HoatDong"/"NgungDung"
        ThuongHieu th = new ThuongHieu();
        th.setTenThuongHieu(ten);
        th.setMoTa(moTa);
        th.setTrangThai(ttDb);
        return th;
    }
    
    private ThuongHieu readFormForUpdate() {
        Integer id = parseIdFromField();
        if (id == null) throw new IllegalArgumentException("ID không hợp lệ");
        ThuongHieu th = readFormForCreate();
        th.setId(id);
        return th;
    }
    
    private Integer parseIdFromField() {
        String s = safeText(txtMaThuongHieu.getText());
        if (s.isEmpty()) return null;
        try {
            return Integer.parseInt(s);
        } catch (NumberFormatException e) {
            return null;
        }
    }
    
    private String mapTrangThaiValueFromCombo() {
        String sel = (String) cboTrangThai.getSelectedItem();
        // Khi thêm/sửa, nếu chọn "Tất cả" -> mặc định "HoatDong"
        if (sel == null || "Tất cả".equals(sel)) return "HoatDong";
        // Hợp lệ: "HoatDong" hoặc "NgungDung"
        return sel;
    }
    
    private boolean safeInsert(ThuongHieu th) {
        try {
            // Giả định DAO trả về ID mới hoặc cập nhật vào entity; nếu không, bỏ selectRowById
            if (thuongHieuDAO instanceof dao.impl.ThuongHieuDAOImpl impl) {
                Integer newId = impl.insert(th); // điều chỉnh nếu khác chữ ký
                if (newId != null) th.setId(newId);
                return newId != null;
            } else {
                // fallback: nếu interface có insert trả boolean
                // return thuongHieuDAO.insert(th);
                // Tùy thuộc dự án của bạn, thay thế đoạn này
                return false;
            }
        } catch (NoSuchMethodError | AbstractMethodError e) {
            // Trường hợp interface khác chữ ký
            return false;
        }
    }
    
    private boolean safeUpdate(ThuongHieu th) {
        try {
            if (thuongHieuDAO instanceof dao.impl.ThuongHieuDAOImpl impl) {
                return impl.update(th); // điều chỉnh nếu chữ ký khác
            } else {
                // return thuongHieuDAO.update(th);
                return false;
            }
        } catch (NoSuchMethodError | AbstractMethodError e) {
            return false;
        }
    }
    
    private boolean safeDelete(Integer id) {
        try {
            if (thuongHieuDAO instanceof dao.impl.ThuongHieuDAOImpl impl) {
                return impl.delete(id);
            } else {
                return false;
            }
        } catch (RuntimeException re) {
            Throwable cause = re.getCause();
            if (cause instanceof SQLException) {
                String state = ((SQLException) cause).getSQLState();
                int code = ((SQLException) cause).getErrorCode();
                // Bắt lỗi ràng buộc FK phổ biến của SQL Server: 547
                if (code == 547) {
                    JOptionPane.showMessageDialog(this,
                        "Không thể xóa do đang được tham chiếu bởi dữ liệu khác (ví dụ: Đồ uống). " +
                        "Hãy cập nhật hoặc xóa dữ liệu liên quan trước, hoặc chuyển trạng thái NgungDung.");
                    return false;
                }
            }
            throw re;
        } catch (NoSuchMethodError | AbstractMethodError e) {
            return false;
        }
    }
    
    private void selectRowById(Integer id) {
        if (id == null) return;
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            Object val = tableModel.getValueAt(i, 0);
            if (val != null && val.toString().equals(String.valueOf(id))) {
                tblThuongHieu.setRowSelectionInterval(i, i);
                tblThuongHieu.scrollRectToVisible(tblThuongHieu.getCellRect(i, 0, true));
                break;
            }
        }
    }

    private void clearForm() {
        txtMaThuongHieu.setText("");
        txtTenThuongHieu.setText("");
        txtMoTa.setText("");
        cboTrangThai.setSelectedIndex(0);
        tblThuongHieu.clearSelection();
        updateButtonStates(false);
    }

    private void clearPlaceholders() {
        if ("jTextField1".equals(txtMaThuongHieu.getText())) txtMaThuongHieu.setText("");
        if ("jTextField1".equals(txtTenThuongHieu.getText())) txtTenThuongHieu.setText("");
        if ("jTextField1".equals(txtSearchThuongHieu.getText())) txtSearchThuongHieu.setText("");
    }

    private String safeText(String s) {
        return s == null ? "" : s.trim();
    }

    private void loadDataToTable(String keyword) {
        List<ThuongHieu> list = thuongHieuDAO.findAll();
        tableModel.setRowCount(0);
        int count = 0;
        String kw = safeText(keyword).toLowerCase();
        String filterTrangThai = mapTrangThaiFilter((String) cboTrangThai.getSelectedItem()); // "HoatDong"/"NgungDung"/null

        for (ThuongHieu th : list) {
            boolean matchKw = kw.isEmpty() || 
                (th.getTenThuongHieu() != null && th.getTenThuongHieu().toLowerCase().contains(kw)) ||
                (th.getMoTa() != null && th.getMoTa().toLowerCase().contains(kw));
            String ttDb = toDbTrangThai(th); // "HoatDong"/"NgungDung"
            boolean matchTrangThai = filterTrangThai == null || filterTrangThai.equals(ttDb);
            if (matchKw && matchTrangThai) {
                tableModel.addRow(new Object[]{
                    th.getId(),
                    th.getTenThuongHieu(),
                    th.getMoTa(),
                    ttDb
                });
                count++;
            }
        }
        lblTongThuongHieu.setText(String.valueOf(count));
    }

    private String mapTrangThaiFilter(String selected) {
        if (selected == null || "Tất cả".equals(selected)) return null;
        // Trả về đúng giá trị DB
        if ("HoatDong".equals(selected)) return "HoatDong";
        if ("NgungDung".equals(selected)) return "NgungDung";
        return null;
    }

    private String toDbTrangThai(ThuongHieu th) {
        Object st = th.getTrangThai();
        if (st == null) return "HoatDong";
        String txt = String.valueOf(st).trim();
        // Chuẩn hóa vài trường hợp
        if ("1".equals(txt) || "true".equalsIgnoreCase(txt) || "Đang dùng".equalsIgnoreCase(txt) || "HoatDong".equalsIgnoreCase(txt))
            return "HoatDong";
        if ("0".equals(txt) || "false".equalsIgnoreCase(txt) || "Ngừng dùng".equalsIgnoreCase(txt) || "NgungDung".equalsIgnoreCase(txt))
            return "NgungDung";
        // Mặc định về HoatDong
        return "HoatDong";
    }
}