/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import dao.KhachHangDAO;
import dao.impl.KhachHangDAOImpl;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import model.KhachHang;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import utils.MsgBox;
import utils.XDate;

/**
 *
 * @author Admin
 */
public class KhachHangForm extends javax.swing.JFrame {

    KhachHangDAO dao = new KhachHangDAOImpl();
    int row = -1; // Hàng đang được chọn

    /**
     * Creates new form KhachHangForm
     */
    public KhachHangForm() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        // Cài đặt và khởi tạo form
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        txtSoDienThoai = new javax.swing.JTextField();
        btnLamMoi = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDiaChi = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNgayDangKy = new javax.swing.JTextField();
        txtSoDonDaMua = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable();
        txtID = new javax.swing.JTextField();
        btnSua = new javax.swing.JButton();
        txtCapDoVIP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        btnXacNhan = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtDiemThuong = new javax.swing.JTextField();
        cboFilterCapDoVIP = new javax.swing.JComboBox<>();
        txtDiemThuongMin = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDiemThuongMax = new javax.swing.JTextField();
        btnApplyFilter = new javax.swing.JButton();
        btnClearFilter = new javax.swing.JButton();
        btnExportExcel = new javax.swing.JButton();
        btnImportExcel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(225, 177, 112));
        jPanel1.setForeground(new java.awt.Color(164, 115, 115));
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 900));

        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });

        txtSoDienThoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoDienThoaiActionPerformed(evt);
            }
        });

        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(164, 115, 115));
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh.png"))); // NOI18N
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThem.setForeground(new java.awt.Color(164, 115, 115));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plus.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(164, 115, 115));
        jLabel9.setText("Ngày đăng kí");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(164, 115, 115));
        jLabel7.setText("Điểm Thưởng");

        txtDiaChi.setColumns(20);
        txtDiaChi.setRows(5);
        jScrollPane1.setViewportView(txtDiaChi);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(164, 115, 115));
        jLabel1.setText("Tìm Kiếm");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(164, 115, 115));
        jLabel2.setText("ID");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(164, 115, 115));
        jLabel10.setText("Số đơn đã mua");

        txtNgayDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayDangKyActionPerformed(evt);
            }
        });

        txtSoDonDaMua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoDonDaMuaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(164, 115, 115));
        jLabel3.setText("Họ và tên");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(164, 115, 115));
        jLabel4.setText("Số điện thoại");

        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Họ Tên", "Số Điện Thoại", "Điểm Thưởng", "Cấp Độ Vip", "Ngày Đăng Kí", "Số Đơn Đã Mua"
            }
        ));
        tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblKhachHang);

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSua.setForeground(new java.awt.Color(164, 115, 115));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fix.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        txtCapDoVIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCapDoVIPActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(164, 115, 115));
        jLabel5.setText("Email");

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(164, 115, 115));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete_one.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnXacNhan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXacNhan.setForeground(new java.awt.Color(164, 115, 115));
        btnXacNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/find.png"))); // NOI18N
        btnXacNhan.setText("Tìm Kiếm");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(164, 115, 115));
        jLabel8.setText("Cấp độ Vip");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(164, 115, 115));
        jLabel6.setText("Địa chỉ");

        txtHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoTenActionPerformed(evt);
            }
        });

        txtDiemThuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiemThuongActionPerformed(evt);
            }
        });

        cboFilterCapDoVIP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cboFilterCapDoVIP.setForeground(new java.awt.Color(164, 115, 115));
        cboFilterCapDoVIP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(164, 115, 115));
        jLabel11.setText("Lọc Min");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(164, 115, 115));
        jLabel12.setText("Lọc Max");

        btnApplyFilter.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnApplyFilter.setForeground(new java.awt.Color(164, 115, 115));
        btnApplyFilter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filter.png"))); // NOI18N
        btnApplyFilter.setText("Áp dụng lọc");

        btnClearFilter.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClearFilter.setForeground(new java.awt.Color(164, 115, 115));
        btnClearFilter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel filter.png"))); // NOI18N
        btnClearFilter.setText("Xóa Bộ Lọc");

        btnExportExcel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExportExcel.setForeground(new java.awt.Color(164, 115, 115));
        btnExportExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/export.png"))); // NOI18N
        btnExportExcel.setText("Xuất Excel");

        btnImportExcel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnImportExcel.setForeground(new java.awt.Color(164, 115, 115));
        btnImportExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add excel.png"))); // NOI18N
        btnImportExcel.setText("Nhập Excel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSoDonDaMua)
                            .addComponent(txtNgayDangKy)
                            .addComponent(txtEmail)
                            .addComponent(txtHoTen)
                            .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(txtSoDienThoai)
                            .addComponent(txtDiemThuong)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txtCapDoVIP))
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnExportExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLamMoi))
                                .addContainerGap())
                            .addComponent(btnImportExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnXacNhan)
                        .addGap(18, 18, 18)
                        .addComponent(cboFilterCapDoVIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDiemThuongMin, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDiemThuongMax, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnApplyFilter)
                        .addGap(18, 18, 18)
                        .addComponent(btnClearFilter)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel6)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel7))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDiemThuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtCapDoVIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNgayDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSoDonDaMua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnThem)
                                    .addComponent(btnSua))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnXoa)
                                    .addComponent(btnLamMoi))
                                .addGap(34, 34, 34)
                                .addComponent(btnExportExcel)
                                .addGap(32, 32, 32)
                                .addComponent(btnImportExcel))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDiemThuongMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txtDiemThuongMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnApplyFilter)
                            .addComponent(btnClearFilter)
                            .addComponent(jLabel11)
                            .addComponent(cboFilterCapDoVIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXacNhan))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1432, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // Khi người dùng nhấn Enter trong ô tìm kiếm, tự động thực hiện tìm kiếm
        search();
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void txtSoDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoDienThoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoDienThoaiActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:\
        clearForm();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtNgayDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayDangKyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayDangKyActionPerformed

    private void txtSoDonDaMuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoDonDaMuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoDonDaMuaActionPerformed

    private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked
        // Khi click vào một hàng, hiển thị chi tiết lên form
        if (evt.getClickCount() == 1) {
            this.row = tblKhachHang.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tblKhachHangMouseClicked

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void txtCapDoVIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapDoVIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapDoVIPActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // Thực hiện tìm kiếm khi nhấn nút
        search();
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void txtHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenActionPerformed

    private void txtDiemThuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemThuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemThuongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhachHangForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhachHangForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhachHangForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhachHangForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhachHangForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApplyFilter;
    private javax.swing.JButton btnClearFilter;
    private javax.swing.JButton btnExportExcel;
    private javax.swing.JButton btnImportExcel;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboFilterCapDoVIP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblKhachHang;
    private javax.swing.JTextField txtCapDoVIP;
    private javax.swing.JTextArea txtDiaChi;
    private javax.swing.JTextField txtDiemThuong;
    private javax.swing.JTextField txtDiemThuongMax;
    private javax.swing.JTextField txtDiemThuongMin;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNgayDangKy;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtSoDonDaMua;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    // =================================================================
    // PHẦN CODE LOGIC DO TÔI THÊM VÀO
    // =================================================================
    
    /**
     * Khởi tạo các giá trị ban đầu cho form
     */
    void init() {
        setLocationRelativeTo(null); // Canh giữa form

        txtID.setEditable(false);
        txtDiemThuong.setEditable(false);
        txtCapDoVIP.setEditable(false);
        txtSoDonDaMua.setEditable(false);
        txtNgayDangKy.setEditable(false);

        // Cấu hình ComboBox lọc
        DefaultComboBoxModel<String> cboModel = new DefaultComboBoxModel<>();
        cboModel.addElement("Tất cả");
        cboModel.addElement("Silver");
        cboModel.addElement("Gold");
        cboModel.addElement("Bronze");
        cboModel.addElement("Diamond");
        cboFilterCapDoVIP.setModel(cboModel);

        // Gắn sự kiện cho các nút mới
        btnApplyFilter.addActionListener(e -> applyFilter());
        btnClearFilter.addActionListener(e -> clearFilter());
        btnExportExcel.addActionListener(e -> exportExcel());
        btnImportExcel.addActionListener(e -> importExcel());
//        btnManageDiscountCodes.addActionListener(e -> manageDiscountCodes());

        fillTable(); // Đổ dữ liệu vào bảng
    }

    /**
     * Đổ toàn bộ dữ liệu từ DB vào bảng
     */
    void fillTable() {
        try {
            List<KhachHang> list = dao.selectAll(); // Lấy tất cả khách hàng
            fillTable(list);
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
            e.printStackTrace();
        }
    }

    /**
     * Đổ dữ liệu từ một danh sách cho trước vào bảng
     * @param list Danh sách khách hàng cần hiển thị
     */
    void fillTable(List<KhachHang> list) {
        DefaultTableModel model = (DefaultTableModel) tblKhachHang.getModel();
        model.setRowCount(0); // Xóa tất cả các hàng
        try {
            for (KhachHang kh : list) {
                Object[] rowData = {
                    kh.getId(),
                    kh.getHoTen(),
                    kh.getSoDienThoai(),
                    kh.getDiemThuong(),
                    kh.getCapDoVIP(),
                    XDate.toString(kh.getNgayDangKy(), "dd/MM/yyyy"),
                    kh.getSoDonDaMua()
                };
                model.addRow(rowData);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi hiển thị dữ liệu!");
            e.printStackTrace();
        }
    }
    
    /**
     * Hiển thị thông tin của một khách hàng lên form
     * @param kh đối tượng KhachHang cần hiển thị
     */
    void setForm(KhachHang kh) {
        txtID.setText(kh.getId() != 0 ? String.valueOf(kh.getId()) : "");
        txtHoTen.setText(kh.getHoTen());
        txtSoDienThoai.setText(kh.getSoDienThoai());
        txtEmail.setText(kh.getEmail());
        txtDiaChi.setText(kh.getDiaChi());
        txtDiemThuong.setText(String.valueOf(kh.getDiemThuong()));
        txtCapDoVIP.setText(kh.getCapDoVIP());
        txtNgayDangKy.setText(XDate.toString(kh.getNgayDangKy(), "dd/MM/yyyy"));
        txtSoDonDaMua.setText(String.valueOf(kh.getSoDonDaMua()));
    }

    /**
     * Lấy thông tin từ form để tạo một đối tượng KhachHang
     * @return đối tượng KhachHang
     */
    KhachHang getForm() {
        KhachHang kh = new KhachHang();
        if (!txtID.getText().isEmpty()) {
            kh.setId(Integer.parseInt(txtID.getText()));
        }
        kh.setHoTen(txtHoTen.getText());
        kh.setSoDienThoai(txtSoDienThoai.getText());
        kh.setEmail(txtEmail.getText());
        kh.setDiaChi(txtDiaChi.getText());
        // Các trường không cho sửa sẽ lấy từ DB hoặc để mặc định
        if (!txtDiemThuong.getText().isEmpty()) {
            kh.setDiemThuong(Integer.parseInt(txtDiemThuong.getText()));
        }
        kh.setCapDoVIP(txtCapDoVIP.getText());
        if (!txtNgayDangKy.getText().isEmpty()) {
            kh.setNgayDangKy(XDate.toDate(txtNgayDangKy.getText(), "dd/MM/yyyy"));
        }
        return kh;
    }

    /**
     * Xóa trắng các trường nhập liệu trên form
     */
    void clearForm() {
        KhachHang kh = new KhachHang();
        kh.setNgayDangKy(new Date());
        kh.setDiemThuong(0);
        kh.setCapDoVIP("Silver");
        kh.setSoDonDaMua(0);
        this.setForm(kh);
        this.row = -1;
    }

    /**
     * Xử lý sự kiện khi một hàng trên bảng được chọn
     */
    void edit() {
        try {
            Integer id = (Integer) tblKhachHang.getValueAt(this.row, 0);
            KhachHang kh = dao.findById(id);
            if (kh != null) {
                this.setForm(kh);
            }
        } catch (Exception e) {
             MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
             e.printStackTrace();
        }
    }
    
    /**
     * Thực hiện tìm kiếm theo từ khóa và đổ lại dữ liệu vào bảng
     */
    void search() {
        try {
            String keyword = txtTimKiem.getText();
            List<KhachHang> list = dao.selectByKeyword(keyword);
            fillTable(list);
            this.clearForm();
            this.row = -1;
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi tìm kiếm!");
            e.printStackTrace();
        }
    }

    /**
     * Thêm khách hàng mới.
     */
    void insert() {
        KhachHang model = getForm();
        // Validate dữ liệu
        if(model.getSoDienThoai().isEmpty()){
            MsgBox.alert(this, "Số điện thoại không được để trống!");
            return;
        }
        try {
            dao.insert(model);
            this.fillTable();
            this.clearForm();
            MsgBox.alert(this, "Thêm mới thành công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Thêm mới thất bại!");
            e.printStackTrace();
        }
    }

    /**
     * Cập nhật thông tin khách hàng.
     */
    void update() {
        KhachHang model = getForm();
        if(model.getSoDienThoai().isEmpty()){
            MsgBox.alert(this, "Số điện thoại không được để trống!");
            return;
        }
        try {
            dao.update(model);
            this.fillTable();
            MsgBox.alert(this, "Cập nhật thành công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Cập nhật thất bại!");
            e.printStackTrace();
        }
    }

    /**
     * Xóa khách hàng.
     */
    void delete() {
        if(txtID.getText().isEmpty()){
             MsgBox.alert(this, "Vui lòng chọn khách hàng cần xóa!");
             return;
        }
        if (MsgBox.confirm(this, "Bạn có thực sự muốn xóa khách hàng này?")) {
            Integer id = Integer.valueOf(txtID.getText());
            try {
                dao.delete(id);
                this.fillTable();
                this.clearForm();
                MsgBox.alert(this, "Xóa thành công!");
            } catch (Exception e) {
                MsgBox.alert(this, "Xóa thất bại!");
                e.printStackTrace();
            }
        }
    }
    
    // =================================================================
    // CÁC HÀM MỚI CHO TÍNH NĂNG MỞ RỘNG
    // =================================================================
    
    /**
     * Áp dụng bộ lọc và hiển thị kết quả
     */
    void applyFilter() {
        String capDoVIP = (String) cboFilterCapDoVIP.getSelectedItem();
        String diemMinStr = txtDiemThuongMin.getText().trim();
        String diemMaxStr = txtDiemThuongMax.getText().trim();

        int diemMin = 0;
        int diemMax = Integer.MAX_VALUE;

        try {
            if (!diemMinStr.isEmpty()) {
                diemMin = Integer.parseInt(diemMinStr);
            }
            if (!diemMaxStr.isEmpty()) {
                diemMax = Integer.parseInt(diemMaxStr);
            }
        } catch (NumberFormatException e) {
            MsgBox.alert(this, "Điểm thưởng phải là một số nguyên!");
            return;
        }

        if (diemMin > diemMax) {
            MsgBox.alert(this, "Điểm thưởng tối thiểu không thể lớn hơn tối đa!");
            return;
        }

        try {
            List<KhachHang> list = dao.filter(capDoVIP, diemMin, diemMax);
            fillTable(list);
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi lọc dữ liệu!");
            e.printStackTrace();
        }
    }

    /**
     * Xóa bộ lọc và hiển thị lại toàn bộ danh sách
     */
    void clearFilter() {
        cboFilterCapDoVIP.setSelectedIndex(0);
        txtDiemThuongMin.setText("");
        txtDiemThuongMax.setText("");
        txtTimKiem.setText("");
        fillTable(); // Tải lại toàn bộ dữ liệu
    }

    /**
     * Xuất dữ liệu ra file Excel.
     */
    void exportExcel() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Lưu file Excel");
        fileChooser.setFileFilter(new FileNameExtensionFilter("Excel Files", "xlsx"));
        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            String filePath = fileToSave.getAbsolutePath();
            if (!filePath.endsWith(".xlsx")) {
                filePath += ".xlsx";
            }
            try (Workbook workbook = new XSSFWorkbook()) {
                Sheet sheet = workbook.createSheet("DanhSachKhachHang");

                // Create header row
                Row headerRow = sheet.createRow(0);
                String[] columns = {"ID", "Họ Tên", "Số Điện Thoại", "Email", "Địa chỉ", "Điểm Thưởng", "Cấp Độ Vip", "Ngày Đăng Kí", "Số Đơn Đã Mua"};
                for (int i = 0; i < columns.length; i++) {
                    Cell cell = headerRow.createCell(i);
                    cell.setCellValue(columns[i]);
                }

                // Create data rows
                List<KhachHang> list = dao.selectAll();
                int rowNum = 1;
                for (KhachHang kh : list) {
                    Row row = sheet.createRow(rowNum++);
                    row.createCell(0).setCellValue(kh.getId());
                    row.createCell(1).setCellValue(kh.getHoTen());
                    row.createCell(2).setCellValue(kh.getSoDienThoai());
                    row.createCell(3).setCellValue(kh.getEmail());
                    row.createCell(4).setCellValue(kh.getDiaChi());
                    row.createCell(5).setCellValue(kh.getDiemThuong());
                    row.createCell(6).setCellValue(kh.getCapDoVIP());
                    row.createCell(7).setCellValue(XDate.toString(kh.getNgayDangKy(), "dd/MM/yyyy"));
                    row.createCell(8).setCellValue(kh.getSoDonDaMua());
                }

                try (FileOutputStream fileOut = new FileOutputStream(filePath)) {
                    workbook.write(fileOut);
                }
                MsgBox.alert(this, "Xuất file Excel thành công!");
            } catch (IOException e) {
                MsgBox.alert(this, "Lỗi khi xuất file Excel!");
                e.printStackTrace();
            }
        }
    }

    /**
     * Nhập dữ liệu từ file Excel.
     */
    void importExcel() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Chọn file Excel");
        fileChooser.setFileFilter(new FileNameExtensionFilter("Excel Files", "xlsx"));
        int userSelection = fileChooser.showOpenDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToRead = fileChooser.getSelectedFile();
            try (FileInputStream fis = new FileInputStream(fileToRead); Workbook workbook = new XSSFWorkbook(fis)) {
                Sheet sheet = workbook.getSheetAt(0);
                for (int i = 1; i <= sheet.getLastRowNum(); i++) {
                    Row row = sheet.getRow(i);
                    if (row != null) {
                        KhachHang kh = new KhachHang();
                        kh.setHoTen(row.getCell(1).getStringCellValue());
                        kh.setSoDienThoai(row.getCell(2).getStringCellValue());
                        kh.setEmail(row.getCell(3).getStringCellValue());
                        kh.setDiaChi(row.getCell(4).getStringCellValue());
                        kh.setDiemThuong((int) row.getCell(5).getNumericCellValue());
                        kh.setCapDoVIP(row.getCell(6).getStringCellValue());
                        kh.setNgayDangKy(XDate.toDate(row.getCell(7).getStringCellValue(), "dd/MM/yyyy"));
                        // Số đơn đã mua thường được tính tự động, không nên cho nhập
                        dao.insert(kh);
                    }
                }
                fillTable();
                MsgBox.alert(this, "Nhập dữ liệu từ Excel thành công!");
            } catch (IOException | NumberFormatException e) {
                MsgBox.alert(this, "Lỗi khi nhập dữ liệu từ file Excel!");
                e.printStackTrace();
            }
        }
    }
    
    /**
     * Mở form quản lý mã giảm giá (chức năng chờ)
     */
    void manageDiscountCodes() {
        MsgBox.alert(this, "Chức năng Quản lý mã giảm giá đang được phát triển!");
        // TODO: Implement logic to open discount code management form
    }
    
    public void refreshTable() {
        fillTable();
    }
    
    /**
     * Sets the phone number field on the form.
     * Called from another form to pre-fill the phone number.
     * @param sdt The phone number to set.
     */
    public void setSoDienThoai(String sdt) {
        txtSoDienThoai.setText(sdt);
    }
}
