/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import com.toedter.calendar.JDateChooser;
import dao.ChiNhanhDAO;
import dao.DoUongDAO;
import dao.LichSuKhoDAO;
import dao.NhanVienDAO;
import dao.impl.ChiNhanhDAOImpl;
import dao.impl.DoUongDAOImpl;
import dao.impl.NhanVienDAOImpl;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ChiNhanh;
import model.DoUong;
import model.LichSuKho;
import model.NhanVien;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import utils.XDate;

/**
 *
 * @author Admin
 */
public class LichSuKhoForm extends javax.swing.JFrame {

    LichSuKhoDAO lichSuKhoDAO;
    ChiNhanhDAO chiNhanhDAO;
    DoUongDAO doUongDAO;
    NhanVienDAO nhanVienDAO;
    DefaultTableModel tblModel;

    /**
     * Creates new form LichSuKhoForm
     */
    public LichSuKhoForm() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cboChiNhanh = new javax.swing.JComboBox<>();
        dateTuNgay = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnLoc = new javax.swing.JButton();
        cboLoaiGiaoDich = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnXuatExcel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLichSuKho = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        dateDenNgay = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTimKiemDoUong = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(880, 653));

        jPanel1.setBackground(new java.awt.Color(225, 177, 112));
        jPanel1.setForeground(new java.awt.Color(164, 115, 115));

        cboChiNhanh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cboChiNhanh.setForeground(new java.awt.Color(164, 115, 115));
        cboChiNhanh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(164, 115, 115));
        jLabel1.setText("Từ ngày");

        btnLoc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLoc.setForeground(new java.awt.Color(164, 115, 115));
        btnLoc.setText("Lọc");
        btnLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocActionPerformed(evt);
            }
        });

        cboLoaiGiaoDich.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cboLoaiGiaoDich.setForeground(new java.awt.Color(164, 115, 115));
        cboLoaiGiaoDich.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(164, 115, 115));
        jLabel5.setText("Tìm Đồ Uống");

        btnXuatExcel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXuatExcel.setForeground(new java.awt.Color(164, 115, 115));
        btnXuatExcel.setText("Xuất Excel");

        tblLichSuKho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Ngày Giao Dịch", "Tên Đồ Uống", "Loại Giao Dịch", "Số Lượng", "Tên Chi Nhánh", "Nhân Viên", "Ghi Chú"
            }
        ));
        jScrollPane1.setViewportView(tblLichSuKho);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(164, 115, 115));
        jLabel2.setText("Đến Ngày");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(164, 115, 115));
        jLabel3.setText("Chi Nhánh");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(164, 115, 115));
        jLabel4.setText("Loại");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel5))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboChiNhanh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dateTuNgay))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboLoaiGiaoDich, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dateDenNgay)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtTimKiemDoUong, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLoc)
                                .addGap(12, 12, 12)))
                        .addGap(66, 66, 66)
                        .addComponent(btnXuatExcel)
                        .addGap(212, 212, 212))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(dateDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboChiNhanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboLoaiGiaoDich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(btnXuatExcel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTimKiemDoUong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(252, 252, 252))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 746, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLocActionPerformed

    void init() {
        setLocationRelativeTo(null);
        lichSuKhoDAO = new LichSuKhoDAO();
        chiNhanhDAO = new ChiNhanhDAOImpl();
        doUongDAO = new DoUongDAOImpl();
        nhanVienDAO = new NhanVienDAOImpl();
        tblModel = (DefaultTableModel) tblLichSuKho.getModel();

        fillComboBoxChiNhanh();
        fillComboBoxLoaiGiaoDich();
        fillTable(lichSuKhoDAO.selectAll());

        btnLoc.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                filterData();
            }
        });

        btnXuatExcel.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                exportToExcel();
            }
        });
    }

    void filterData() {
        String tuNgay = null;
        String denNgay = null;

        try {
            if (!dateTuNgay.getText().trim().isEmpty()) {
                Date d = XDate.toDate(dateTuNgay.getText().trim(), "dd/MM/yyyy");
                tuNgay = XDate.toString(d, "yyyy-MM-dd");
            }
            if (!dateDenNgay.getText().trim().isEmpty()) {
                Date d2 = XDate.toDate(dateDenNgay.getText().trim(), "dd/MM/yyyy");
                denNgay = XDate.toString(d2, "yyyy-MM-dd");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Định dạng ngày không hợp lệ. Vui lòng nhập dd/MM/yyyy");
            return;
        }

        Integer chiNhanhId = null;
        if (cboChiNhanh.getSelectedIndex() > 0) {
            ChiNhanh selectedChiNhanh = (ChiNhanh) cboChiNhanh.getSelectedItem();
            chiNhanhId = selectedChiNhanh.getId();
        }

        String loaiGiaoDich = null;
        if (cboLoaiGiaoDich.getSelectedIndex() > 0) {
            loaiGiaoDich = (String) cboLoaiGiaoDich.getSelectedItem();
        }

        String tenDoUong = txtTimKiemDoUong.getText().trim();

        List<LichSuKho> list = lichSuKhoDAO.filter(tuNgay, denNgay, chiNhanhId, loaiGiaoDich, tenDoUong);
        fillTable(list);
    }

    void exportToExcel() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Specify a file to save");
        // Set default file name
        fileChooser.setSelectedFile(new File(System.getProperty("user.home") + "/Documents/LichSuKho.xlsx"));

        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            try (Workbook workbook = new XSSFWorkbook(); FileOutputStream fos = new FileOutputStream(fileToSave)) {
                Sheet sheet = workbook.createSheet("LichSuKho");

                // Create header row
                Row headerRow = sheet.createRow(0);
                for (int i = 0; i < tblLichSuKho.getColumnCount(); i++) {
                    Cell cell = headerRow.createCell(i);
                    cell.setCellValue(tblLichSuKho.getColumnName(i));
                }

                // Create data rows
                for (int i = 0; i < tblLichSuKho.getRowCount(); i++) {
                    Row row = sheet.createRow(i + 1);
                    for (int j = 0; j < tblLichSuKho.getColumnCount(); j++) {
                        Cell cell = row.createCell(j);
                        Object value = tblLichSuKho.getValueAt(i, j);
                        if (value != null) {
                            cell.setCellValue(value.toString());
                        }
                    }
                }

                workbook.write(fos);
                JOptionPane.showMessageDialog(this, "Exported successfully to " + fileToSave.getAbsolutePath());
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error exporting to Excel", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    void fillComboBoxChiNhanh() {
        DefaultComboBoxModel cboModel = (DefaultComboBoxModel) cboChiNhanh.getModel();
        cboModel.removeAllElements();
        cboModel.addElement("Tất cả chi nhánh");
        List<ChiNhanh> list = chiNhanhDAO.findAll();
        for (ChiNhanh cn : list) {
            cboModel.addElement(cn);
        }
         cboChiNhanh.setRenderer(new javax.swing.ListCellRenderer<Object>() {
            @Override
            public java.awt.Component getListCellRendererComponent(javax.swing.JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                if (value instanceof ChiNhanh) {
                    ChiNhanh cn = (ChiNhanh) value;
                    return new javax.swing.JLabel(cn.getTenChiNhanh());
                }
                return new javax.swing.JLabel(value.toString());
            }
        });
    }

    void fillComboBoxLoaiGiaoDich() {
        DefaultComboBoxModel cboModel = (DefaultComboBoxModel) cboLoaiGiaoDich.getModel();
        cboModel.removeAllElements();
        cboModel.addElement("Tất cả loại giao dịch");
        cboModel.addElement("Nhập");
        cboModel.addElement("Xuất");
        cboModel.addElement("Kiểm kho");
    }

    void fillTable(List<LichSuKho> list) {
        tblModel.setRowCount(0);
        try {
            for (LichSuKho lsk : list) {
                DoUong du = doUongDAO.selectById(lsk.getDoUongID());
                ChiNhanh cn = chiNhanhDAO.findById(lsk.getChiNhanhID());
                NhanVien nv = nhanVienDAO.findById(lsk.getNhanVienID());
                Object[] row = {
                    lsk.getId(),
                    new SimpleDateFormat("dd-MM-yyyy HH:mm:ss").format(lsk.getNgayGiaoDich()),
                    du != null ? du.getTenDoUong() : "N/A",
                    lsk.getLoaiGiaoDich(),
                    lsk.getSoLuong(),
                    cn != null ? cn.getTenChiNhanh() : "N/A",
                    nv != null ? nv.getHoTen() : "N/A",
                    lsk.getGhiChu()
                };
                tblModel.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading data", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LichSuKhoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LichSuKhoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LichSuKhoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LichSuKhoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LichSuKhoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoc;
    private javax.swing.JButton btnXuatExcel;
    private javax.swing.JComboBox<String> cboChiNhanh;
    private javax.swing.JComboBox<String> cboLoaiGiaoDich;
    private javax.swing.JTextField dateDenNgay;
    private javax.swing.JTextField dateTuNgay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLichSuKho;
    private javax.swing.JTextField txtTimKiemDoUong;
    // End of variables declaration//GEN-END:variables
}